### ISSUE TITLE
undefined symbol: ndpi_init_detection_module

### ISSUE THREAD

**Issue by betolj** [lmangani/node-ndpi#3]
Hi, I'm trying to integrate your project with nfqueue to create a node-ndpinetfilter

1. I compiled with the latest ndpi version.

2. When compile node-ndpi:

make: Entering directory 'node-ndpi/build'
  CC(target) Release/obj.target/napi_ndpi/ndpiexlib.o
../ndpiexlib.c:448:13: warning: ‘printResults’ defined but not used [-Wunused-function]
 static void printResults(void)
             ^~~~~~~~~~~~
../ndpiexlib.c:68:16: warning: ‘_pcap_handle’ defined but not used [-Wunused-variable]
 static pcap_t *_pcap_handle = NULL;
                ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/napi_ndpi.node
  COPY Release/napi_ndpi.node
make: Leaving directory '/root/node-ndpi/build'
gyp info ok 

3. When i call ndpi.init():
node-ndpi/build/Release/napi_ndpi.node: undefined symbol: ndpi_init_detection_module

Any idea?

**Comment by lmangani** [comment]
My guess is something has changed in the library and needs to be reflected in the binding. I'm not actively maintaining this and might only check this out when time allows, so if you're in a rush for something working and well designed I'd suggest considering: https://github.com/libpeafowl/node-peafowl

**Comment by kYroL01** [comment]
Hello @betolj 

First of all it seems that your application does not call `printResults` and `_pcap_handle` (this is why the _warnings_)
Then, ndpi.init() does not found `ndpi_init_detection_module` in her _body_. I think probably because as @lmangani said, there are various changed in nDPI since this library was built.

**Comment by betolj** [comment]
Ok, i'll try with node-peafowl.
Anyway, congratulations on the project.

Thanks for the answers.
